Code increment #9
AxMdv/go-url-shortener pull request #10
Opened 2024-07-05 13:13 UTC by AxMdv

2024-07-09 16:51 UTC, capsulated requested changes
В общем всё очень даже неплохо!

Оставил пару замечаний, главные из которых вынести мидлвари и пару по неймингу и структуре объектов в приложении

2024-07-09 16:51 UTC, capsulated commented on internal/app/logger/logger.go
> +type (
Всё, что связано с логгингом запросов нужно вынести в отдельный пакет для миддлварей. Хороший пример у [chi](https://github.com/go-chi/chi/tree/master/middleware)

2024-07-09 16:51 UTC, capsulated commented on internal/app/handlers/handlers.go
> +func InitShortenerHandlers(filename string) (*ShortenerHandlers, error) {
Имена конструкторов принято называть с префиксом `New`, рекомендации сообщетва [тут](https://go.dev/doc/effective_go#composite_literals)

2024-07-09 16:51 UTC, capsulated commented on internal/app/handlers/handlers.go
> +	Repository *storage.Repository
👍 И нейминг отличный как для поля, так и для самого типа хендлеров

2024-07-09 16:51 UTC, capsulated commented on cmd/shortener/main.go
> +	r.Post("/", logger.WithLogging(compress.GzipMiddleware(s.CreateShortURL)))
Можно было бы убрать в отдельный тип или функцию. Но пока небольших размеров - то можно и оставить. Так что в будущем смотри, если начнёт "разбухать", то пора переносить в отдельный тип с конструктором `NewRouter() (*Router, error)` в том же пакете хендлеров, к примеру

2024-07-09 16:51 UTC, capsulated commented on internal/app/compress/gzip.go
> +package compress
Можно не только из internal вынести в корень, а даже в `pkg/compress`, чтобы можно было потом в выпускном или pet проекте импортировать

2024-07-09 16:51 UTC, capsulated commented on internal/app/compress/gzip.go
> +func GzipMiddleware(h http.HandlerFunc) http.HandlerFunc {
А эту функцию перенести в отдельный пакет `middleware`. И его, кстати, через тоже в `pkg/middleware` тоже можно, он хороший претендент для переиспользования

2024-07-09 16:51 UTC, capsulated commented on internal/app/logger/logger.go
> +func WithLogging(h http.HandlerFunc) http.HandlerFunc {
Да, вот ещё одна милддлварь

2024-07-09 16:51 UTC, capsulated commented on internal/app/model/request.go
> +type Request struct {
Эти типы в пакет хендлеров переместить можно. Пока типы не используются в многих пакетах, то и выделять их в отдельный пакет моделей (или entity, или domain и тп)  - лишнее, так как только усложняет структуру программы и усложняет чтение. Как только новый тип начинает использоваться во многих пакетах - тогда и надо начинать выносить в виде глобальных `моделей` или `сущностей` программы

2024-07-09 16:51 UTC, capsulated commented on internal/app/storage/storage.go
> +func InitRepository(filename string) (*Repository, error) {
Это уже конструктор (функция пакета, которая инициализирует конкретный и возвращает указатель на экземпляр). Классический конструктор в `go` реализуется паттерном `фабричный метод` и именуется с префиксом `New` (ссылку на рекомендации комьюнити по неймингу в комментарии выше)

2024-07-09 16:51 UTC, capsulated commented on internal/app/storage/storage.go
> +type URLSaver struct {
Круто, что добавил отдельные новые типы для этой логики 🔥

2024-07-10 20:56 UTC, AxMdv commented on internal/app/compress/gzip.go
> +func GzipMiddleware(h http.HandlerFunc) http.HandlerFunc {
Тут немного не понимаю, функция GzipMiddleware использует сущности из пакета compress, который ты выше сказал перенести в pkg/compress. В таком случае придется импортировать данный пакет в pkg/middleware, чтобы функция работала.  Мне кажется, что дополнительная зависимость в пакете избыточна. Прошу поправить меня, если в чем-то не прав.  
P.s. по итогу я сделал как у chi - логгер и компрессор переместил в pkg/middleware, просто разными файлами

2024-07-10 21:00 UTC, AxMdv commented on cmd/shortener/main.go
> +	r.Post("/", logger.WithLogging(compress.GzipMiddleware(s.CreateShortURL)))
Да, согласен. Пока что это основные функции приложения, которых немного и хотелось, чтобы они были перед глазами в мейне)

2024-07-11 23:40 UTC, capsulated reviewed
Пару замечаний ещё написал. Они по структуре объектов, просто переместить пару кусков кода по пакетам. Апрувлю, и тогда в начале следующего спринта надо пофиксить, а то по дедлайнам не успеем

2024-07-11 23:40 UTC, capsulated commented on cmd/shortener/main.go
> +	err = middleware.InitLogger()
Так, вот логгер надо бы вынести в отдельный пакет. Всё же он должен использоваться на всех слоях приложения, а не только в мидлваре

2024-07-11 23:40 UTC, capsulated commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
`return`'а не хватает же 🤔

2024-07-11 23:40 UTC, capsulated commented on pkg/middleware/logger.go
> +var Log *zap.Logger = zap.NewNop()
Логгер, да, надо в отдельном пакете инициализировать, а не в middleware

2024-07-11 23:40 UTC, capsulated commented on pkg/middleware/gzip.go
> +type compressWriter struct {
Отдельный пакет `compress` можно сделать. 

Будет в итоге что-то такое:
```sh
pkg/compressor
pkg/logger
pkg/middlware/gzip.go
pkg/middlware/logger.go
```

2024-07-11 23:40 UTC, capsulated commented on pkg/middleware/logger.go
> +func InitLogger() error {
Вот это тоже в пакет для логгера

2024-07-12 14:02 UTC, merged