Code increment #13
AxMdv/go-url-shortener pull request #14
Opened 2024-07-20 15:50 UTC by AxMdv

2024-07-23 21:04 UTC, capsulated requested changes
Вообщем, всё хорошо. Есть несколько замечаний по именам файлов и по добавлению сервисного слоя (добавить в текущем или следующих спринтах), про batch вопрос важный

Если что-то непонятно или спорно - спиши в подгруппу, всё разберём

2024-07-23 21:04 UTC, capsulated commented on cmd/shortener/main.go
> +	r.Get("/{shortenedURL}", middleware.WithLogging(s.GetLongURL))
Инициализацию роутера хорошо бы уже перенести хотя бы просто в функцию в пакет, к примеру, хендлер

2024-07-23 21:04 UTC, capsulated commented on internal/app/handlers/handlers.go
> +	err = s.Repository.AddURL(formedURL)
Хорошо бы сервисный слой добавить, в котором будет вызов методов хранилки, возможно retry и тп. А в хендлерах только методы этот воркера использовать и обрабатывать входные и выходные данные, связнанные именно с риквестом, респонсом, статусами и тп. Что-то типа `ShortenerService.CreateShort()`

Это рекомендация, по желанию, если есть время. Можно и в будущих спринтах. Но с масштабированием хендлеров есть высокая вероятность, что это пригодится. Как и практика  по добавлению слоёв

2024-07-23 21:04 UTC, capsulated commented on internal/app/handlers/handlers.go
> +	err := s.Repository.AddURL(formedURL)
Тут также, претендент на переезд в тот же сервисный слой  с хранилкой

2024-07-23 21:04 UTC, capsulated commented on internal/app/handlers/handlers.go
> +	for i, v := range requestBatch.BatchList {
Такие преобразования можно к модели добавить, назначить метода для структуры, который из одного формата в другой будет преобразовывать

2024-07-23 21:04 UTC, capsulated commented on internal/app/handlers/models.go
> +type RequestBatch struct {
Метода для преобразования дожно добавить к типу, к примеру: `func (rb *RequestBatch) ToJson(...) (string, error)`

2024-07-23 21:04 UTC, capsulated commented on internal/app/model/batch.go
> +package model
А почему модели дблируются? Они же глобальные должны быть, если это модели

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/dbRepository.go
`snake_case.go` файлы именуются по рекомендациям комьюнити

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/dbRepository.go
> +	for _, v := range formedURL {
А почему в цикле в транзакции выбрал решение? Есть же у pgx [batch](https://github.com/jackc/pgx/blob/master/batch_test.go)

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/dbRepository.go
> +	result, err := dr.DB.ExecContext(context.Background(), query, formedURL.ShortenedURL, formedURL.LongURL, formedURL.UIID)
По идее, контекст должен быть передан со стороны вызова, первым параметром метода

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/fileRepository.go
snake_case

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/postgres.go
> +func PingDatabase(config config.Options) error {
Это можно интерфейсы поделить: `Storage`, `Pinger`, `Closer` и проверять, если соотвествует экземпляр хранилки интерфейсу и вызывать метод ping или close, если соответствует

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/ramRepository.go
в snake_case переименовать очень желательно

2024-07-23 21:04 UTC, capsulated commented on internal/app/storage/ramRepository.go
> +func (rr *RAMRepository) Close() error {
Пустые методы реализовывать, чтобы удовлетворить интерфейсу - антипаттерн. Выше писал, что можно проверять на соответствие интерфейсу

2024-07-23 21:04 UTC, capsulated commented on pkg/middleware/logger.go
> -func InitLogger() error {
супер 💪

2024-07-23 21:04 UTC, capsulated commented on tmp/short-url-db.json
пустой, удалить из репозитория

2024-07-25 22:14 UTC, AxMdv commented
Вроде все замечания исправил. С контекстом понимаю, что он должен из хендлера наследоваться, но пока не понял, как его прикрутить. Добавил сервисный слой, также попробовал сделать DI контейнер.

2024-07-26 10:22 UTC, AxMdv commented
По поводу batch: в тз было сказано избежать гонки в БД. Я так и не нашел материала в курсе, где описано как избежать ее. Предположил что транзакция в этом поможет + хотел использовать tx.PrepareContext для производительности (его я забыл реализовать, но в этой редакции сделал). В общем, я сделал в цикле транзакцию просто потому что такой способ был в курсе, без дополнительного изучения этой темы. Был бы признателен, если укажешь, как лучше

2024-07-28 02:02 UTC, capsulated approved these changes
Оставил несколько комментариев

Апрувлю, но в следующем спринте надо подумать над инициализацией, восстановить работу над юнит тестами. И вопрос по serviceProvider

2024-07-28 02:02 UTC, capsulated commented on cmd/shortener/main.go
> +	// cfg := config.ParseOptions()
Комменты лишние, лучше удалить

2024-07-28 02:02 UTC, capsulated commented on internal/app/app.go
> +func (a *App) initDeps() error {
Сложная конструкция инициализации... Я бы всё в конструктор перенёс, оставив только методы запуска (и остановки, если необходимо)

А если уж очень хочется контейнер для зависимостей, то лучше сразу [dig от uber](https://pkg.go.dev/go.uber.org/dig) использовать. Ещё есть [статья](https://golangforall.com/ru/post/dependency-injection.html) интересная на эту тему 

Проблема с зависимостями возникает при их большом количестве. Многие микросервисы состоят из небольшого количества объектов, поэтому нет необходимость в контейнере. Но бывают, конечно, и крупные, скажем, десктопные приложения - в таком случае можно задуматься о контейнере DI

2024-07-28 02:02 UTC, capsulated commented on internal/mocks/mockDbRepository.go
Тоже в camelCase) А вообще, нельзя рядом с хранилкой и положить, в тот же пакет? К примеру: `storage/mock_repository.go` или `storage/db_repository_mock.go`

2024-07-28 02:02 UTC, capsulated commented on internal/app/service_provider.go
> +type serviceProvider struct {
Не совсем пойму, для чего эта структура? Нужно небольшое описание))

2024-07-28 02:02 UTC, capsulated commented on internal/handlers/cookies.go
Пустой?

2024-07-28 02:02 UTC, capsulated commented on internal/handlers/cookies.go
И куки же нужны в middleware 🤔

2024-07-28 02:02 UTC, capsulated commented on internal/handlers/handlers_test.go
> +// func TestServerConnector_CreateShortURL(t *testing.T) {
Не захотелось переписывать? )) В последних спринтах будет повышаться требование к количеству покрытия тестами, чуть ли не до 90%)

2024-07-28 02:02 UTC, capsulated commented on internal/service/service.go
> +type ShortenerService interface {
Интерфейс в месте реализации, а не потребителя: https://go.dev/wiki/CodeReviewComments#interfaces

2024-07-28 14:26 UTC, merged