Code increment #23
AxMdv/go-url-shortener pull request #24
Opened 2024-11-21 12:50 UTC by AxMdv

2024-12-24 18:08 UTC, AxMdv commented
Привет) я переписал приложение немного (перенес интерфейсы в места использования, а не реализации, как было раньше).  Автотесты после рефакторинга пройдены (коммит [996c4df](https://github.com/AxMdv/go-url-shortener/pull/24/commits/996c4dfb92e8d6b393b4548b0fd3f5fe79a27611). 
Далее после добавления graceful shutdown автотесты перестали проходиться. Локально все работает, но в github actions на 12 инкременте автотест зависает и никакой инфы о причине зависания я не могу получить . В остальном проект по ТЗ соответствует.

2025-01-11 16:08 UTC, Bazys requested changes
1. после log.Panic никакой код выполняться не будет
2. хоть это и учебный проект, но лучше сразу не приучаться хранить secretKey в коде или конфигах
3. на ошибку DeleteURLBatch(deleteBatch) проверяешь только в тестах, а в самом боевом испольвании, нет.
4. в нескольких мествах у тебя можно преаллоцировать слайс, за одно и после проверить прыилировщиком, как повлияла.

2025-01-11 16:08 UTC, Bazys commented on internal/storage/ram_repository.go
> +func (rr *RAMRepository) DeleteURLBatch(ctx context.Context, formedURL []model.FormedURL) error {
Параметр функции, названный `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2025-01-11 16:08 UTC, Bazys commented on internal/service/delete.go
> +	var formedToDelete []model.FormedURL
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
sliceTypes := make([]model.FormedURL, 0, len(formResultCh))
```formedToDelete
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2025-01-11 18:42 UTC, AxMdv commented on internal/storage/ram_repository.go
> +func (rr *RAMRepository) DeleteURLBatch(ctx context.Context, formedURL []model.FormedURL) error {
Исправил, второй вариант как раз подошел, т.к соответствовать интерфейсу необходимо.

2025-01-11 18:43 UTC, AxMdv commented on internal/service/delete.go
> +	var formedToDelete []model.FormedURL
Тоже сделал + ещё в одном месте.

2025-01-11 18:47 UTC, AxMdv commented
> 1. после log.Panic никакой код выполняться не будет
> 2. хоть это и учебный проект, но лучше сразу не приучаться хранить secretKey в коде или конфигах
> 3. на ошибку DeleteURLBatch(deleteBatch) проверяешь только в тестах, а в самом боевом испольвании, нет.
> 4. в нескольких мествах у тебя можно преаллоцировать слайс, за одно и после проверить прыилировщиком, как повлияла.

1. Согласен, исправил во всем проекте такие места.
2. Тут конечно не очень ясно, ключ то мне в любом случае нужен для подписания куки и он должен быть постоянным (изначально не было предусмотрено обновление по типу рефреш токенов). 
3. Исправил
4. Исправил

2025-01-13 18:12 UTC, merged